"""Add last_login_at to Student

Revision ID: 5c7494f3ffd5
Revises: 67618fa3562d
Create Date: 2026-07-31 21:41:23.425120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7494f3ffd5'
down_revision = '67618fa3562d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('avatar_filename')

    # ### end Alembic commands ###
