"""Add failed_login_attempts and locked_until to Student

Revision ID: 67618fa3562d
Revises: a9a6d1a98ad3
Create Date: 2026-07-30 20:14:13.505727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67618fa3562d'
down_revision = 'a9a6d1a98ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
